name: deployDev
on:
  push:
    branches: [develop]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APP__HOST }}
          username: ${{ secrets.APP__USER }}
          password: ${{ secrets.APP__SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd ../home/user/web/devTsunami.fulljamdev.fr/public_html/tsunami-judo-club
            && git pull
            && COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader -n 
            && APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear 
            && php bin/console d:m:m --no-interaction 
            
            
